// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Answer defines model for Answer.
type Answer struct {
	Answer     *string `json:"answer,omitempty"`
	AnswerUUID *string `json:"answerUUID,omitempty"`
}

// AnswerReceivedResponse defines model for AnswerReceivedResponse.
type AnswerReceivedResponse struct {
	Message *string `json:"message,omitempty"`
}

// AnswerRequest defines model for AnswerRequest.
type AnswerRequest struct {
	Answer *string `json:"answer,omitempty"`
}

// AnswerWithVotes defines model for AnswerWithVotes.
type AnswerWithVotes struct {
	Answer     *string     `json:"answer,omitempty"`
	AnswerUUID *string     `json:"answerUUID,omitempty"`
	Votes      *[]VoteUser `json:"votes,omitempty"`
}

// AnswersResponse defines model for AnswersResponse.
type AnswersResponse struct {
	Answers *[]Answer `json:"answers,omitempty"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Username *string `json:"username,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// GameCreatedResponse defines model for GameCreatedResponse.
type GameCreatedResponse struct {
	GameId *string `json:"gameId,omitempty"`
}

// GameFinishedResponse defines model for GameFinishedResponse.
type GameFinishedResponse struct {
	Message *string `json:"message,omitempty"`
}

// GameStartedResponse defines model for GameStartedResponse.
type GameStartedResponse struct {
	Message *string `json:"message,omitempty"`
}

// GameStatusResponse defines model for GameStatusResponse.
type GameStatusResponse struct {
	GameMasterUUID *string `json:"gameMasterUUID,omitempty"`

	// ReceivedAnswers Get the number of answers received from the players
	ReceivedAnswers *int `json:"receivedAnswers,omitempty"`

	// Status Status of the game
	Status *int    `json:"status,omitempty"`
	Users  *[]User `json:"users,omitempty"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Status *string `json:"status,omitempty"`
}

// JoinGameResponse defines model for JoinGameResponse.
type JoinGameResponse struct {
	Message *string `json:"message,omitempty"`
}

// NextRoundResponse defines model for NextRoundResponse.
type NextRoundResponse struct {
	Message *string `json:"message,omitempty"`
}

// PlayOrderResponse defines model for PlayOrderResponse.
type PlayOrderResponse struct {
	PlayOrder *[]PlayOrderUser `json:"playOrder,omitempty"`
}

// PlayOrderSetResponse defines model for PlayOrderSetResponse.
type PlayOrderSetResponse struct {
	Message *string `json:"message,omitempty"`
}

// PlayOrderUser defines model for PlayOrderUser.
type PlayOrderUser struct {
	Place    *int    `json:"place,omitempty"`
	UserUUID *string `json:"userUUID,omitempty"`
	Username *string `json:"username,omitempty"`
}

// RevealVotesResponse defines model for RevealVotesResponse.
type RevealVotesResponse struct {
	Answers *[]AnswerWithVotes `json:"answers,omitempty"`
}

// SelectValidAnswersRequest defines model for SelectValidAnswersRequest.
type SelectValidAnswersRequest struct {
	ValidAnswers *[]string `json:"validAnswers,omitempty"`
}

// SetPlayOrderRequest defines model for SetPlayOrderRequest.
type SetPlayOrderRequest struct {
	PlayOrder *[]struct {
		Place    *int    `json:"place,omitempty"`
		UserUUID *string `json:"userUUID,omitempty"`
	} `json:"playOrder,omitempty"`
}

// User defines model for User.
type User struct {
	UserUUID *string `json:"userUUID,omitempty"`
	Username *string `json:"username,omitempty"`
}

// UserToken defines model for UserToken.
type UserToken struct {
	// UserToken Used as Bearer token for authentication
	UserToken *string `json:"userToken,omitempty"`
	UserUUID  *string `json:"userUUID,omitempty"`
}

// ValidAnswersSelectedResponse defines model for ValidAnswersSelectedResponse.
type ValidAnswersSelectedResponse struct {
	Message *string `json:"message,omitempty"`
}

// VoteRecordedResponse defines model for VoteRecordedResponse.
type VoteRecordedResponse struct {
	Message *string `json:"message,omitempty"`
}

// VoteRequest defines model for VoteRequest.
type VoteRequest struct {
	AnswerUUID *string `json:"answerUUID,omitempty"`
}

// VoteUser defines model for VoteUser.
type VoteUser struct {
	UserUUID *string `json:"userUUID,omitempty"`
	Username *string `json:"username,omitempty"`
}

// PostApiCreateUserJSONRequestBody defines body for PostApiCreateUser for application/json ContentType.
type PostApiCreateUserJSONRequestBody = CreateUserRequest

// PostApiGameGameIdAnswersJSONRequestBody defines body for PostApiGameGameIdAnswers for application/json ContentType.
type PostApiGameGameIdAnswersJSONRequestBody = AnswerRequest

// PostApiGameGameIdAnswersSelectValidsJSONRequestBody defines body for PostApiGameGameIdAnswersSelectValids for application/json ContentType.
type PostApiGameGameIdAnswersSelectValidsJSONRequestBody = SelectValidAnswersRequest

// PostApiGameGameIdVoteJSONRequestBody defines body for PostApiGameGameIdVote for application/json ContentType.
type PostApiGameGameIdVoteJSONRequestBody = VoteRequest

// PutApiOrderGameIdJSONRequestBody defines body for PutApiOrderGameId for application/json ContentType.
type PutApiOrderGameIdJSONRequestBody = SetPlayOrderRequest
