// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a game tied to a user
	// (POST /api/create/game)
	CreateGame(c *gin.Context)
	// Create a new user
	// (POST /api/create/user)
	CreateUser(c *gin.Context)
	// Get the answers for the game
	// (GET /api/game/{gameId}/answers)
	GetAnswers(c *gin.Context, gameId string)
	// Send an answer for the game
	// (POST /api/game/{gameId}/answers)
	SendAnswer(c *gin.Context, gameId string)
	// Select valid answers for the game
	// (PUT /api/game/{gameId}/answers/selectValids)
	SelectValidAnswers(c *gin.Context, gameId string)
	// Finish the game
	// (POST /api/game/{gameId}/finish)
	FinishGame(c *gin.Context, gameId string)
	// Move to the next round in the game
	// (POST /api/game/{gameId}/next)
	NextRound(c *gin.Context, gameId string)
	// Mark a player as still connected
	// (POST /api/game/{gameId}/ping)
	PingGame(c *gin.Context, gameId string)
	// Kick a player from a game
	// (DELETE /api/game/{gameId}/players/{userUUID})
	KickPlayer(c *gin.Context, gameId string, userUUID UUID)
	// Reveal the answers and votes in the game
	// (GET /api/game/{gameId}/reveal)
	RevealVotes(c *gin.Context, gameId string)
	// Reveal votes for the current round
	// (POST /api/game/{gameId}/reveal)
	TriggerReveal(c *gin.Context, gameId string)
	// Start the game
	// (POST /api/game/{gameId}/start)
	StartGame(c *gin.Context, gameId string)
	// Start voting for the current round
	// (POST /api/game/{gameId}/startVoting)
	StartVoting(c *gin.Context, gameId string)
	// Get the status of the game
	// (GET /api/game/{gameId}/status)
	GetGameStatus(c *gin.Context, gameId string)
	// Vote for an answer in the game
	// (POST /api/game/{gameId}/vote)
	VoteForAnswer(c *gin.Context, gameId string)
	// Health check
	// (GET /api/health)
	HealthCheck(c *gin.Context)
	// Join a game
	// (POST /api/join/{gameId})
	JoinGame(c *gin.Context, gameId string)
	// Gets the play order of the users for the game
	// (GET /api/order/{gameId})
	GetPlayOrder(c *gin.Context, gameId string)
	// Set the play order for the game
	// (PUT /api/order/{gameId})
	SetPlayOrder(c *gin.Context, gameId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateGame operation middleware
func (siw *ServerInterfaceWrapper) CreateGame(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateGame(c)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateUser(c)
}

// GetAnswers operation middleware
func (siw *ServerInterfaceWrapper) GetAnswers(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAnswers(c, gameId)
}

// SendAnswer operation middleware
func (siw *ServerInterfaceWrapper) SendAnswer(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SendAnswer(c, gameId)
}

// SelectValidAnswers operation middleware
func (siw *ServerInterfaceWrapper) SelectValidAnswers(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SelectValidAnswers(c, gameId)
}

// FinishGame operation middleware
func (siw *ServerInterfaceWrapper) FinishGame(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.FinishGame(c, gameId)
}

// NextRound operation middleware
func (siw *ServerInterfaceWrapper) NextRound(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.NextRound(c, gameId)
}

// PingGame operation middleware
func (siw *ServerInterfaceWrapper) PingGame(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PingGame(c, gameId)
}

// KickPlayer operation middleware
func (siw *ServerInterfaceWrapper) KickPlayer(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "userUUID" -------------
	var userUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userUUID", c.Param("userUUID"), &userUUID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userUUID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.KickPlayer(c, gameId, userUUID)
}

// RevealVotes operation middleware
func (siw *ServerInterfaceWrapper) RevealVotes(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevealVotes(c, gameId)
}

// TriggerReveal operation middleware
func (siw *ServerInterfaceWrapper) TriggerReveal(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TriggerReveal(c, gameId)
}

// StartGame operation middleware
func (siw *ServerInterfaceWrapper) StartGame(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartGame(c, gameId)
}

// StartVoting operation middleware
func (siw *ServerInterfaceWrapper) StartVoting(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartVoting(c, gameId)
}

// GetGameStatus operation middleware
func (siw *ServerInterfaceWrapper) GetGameStatus(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGameStatus(c, gameId)
}

// VoteForAnswer operation middleware
func (siw *ServerInterfaceWrapper) VoteForAnswer(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.VoteForAnswer(c, gameId)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HealthCheck(c)
}

// JoinGame operation middleware
func (siw *ServerInterfaceWrapper) JoinGame(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.JoinGame(c, gameId)
}

// GetPlayOrder operation middleware
func (siw *ServerInterfaceWrapper) GetPlayOrder(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPlayOrder(c, gameId)
}

// SetPlayOrder operation middleware
func (siw *ServerInterfaceWrapper) SetPlayOrder(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetPlayOrder(c, gameId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/create/game", wrapper.CreateGame)
	router.POST(options.BaseURL+"/api/create/user", wrapper.CreateUser)
	router.GET(options.BaseURL+"/api/game/:gameId/answers", wrapper.GetAnswers)
	router.POST(options.BaseURL+"/api/game/:gameId/answers", wrapper.SendAnswer)
	router.PUT(options.BaseURL+"/api/game/:gameId/answers/selectValids", wrapper.SelectValidAnswers)
	router.POST(options.BaseURL+"/api/game/:gameId/finish", wrapper.FinishGame)
	router.POST(options.BaseURL+"/api/game/:gameId/next", wrapper.NextRound)
	router.POST(options.BaseURL+"/api/game/:gameId/ping", wrapper.PingGame)
	router.DELETE(options.BaseURL+"/api/game/:gameId/players/:userUUID", wrapper.KickPlayer)
	router.GET(options.BaseURL+"/api/game/:gameId/reveal", wrapper.RevealVotes)
	router.POST(options.BaseURL+"/api/game/:gameId/reveal", wrapper.TriggerReveal)
	router.POST(options.BaseURL+"/api/game/:gameId/start", wrapper.StartGame)
	router.POST(options.BaseURL+"/api/game/:gameId/startVoting", wrapper.StartVoting)
	router.GET(options.BaseURL+"/api/game/:gameId/status", wrapper.GetGameStatus)
	router.POST(options.BaseURL+"/api/game/:gameId/vote", wrapper.VoteForAnswer)
	router.GET(options.BaseURL+"/api/health", wrapper.HealthCheck)
	router.POST(options.BaseURL+"/api/join/:gameId", wrapper.JoinGame)
	router.GET(options.BaseURL+"/api/order/:gameId", wrapper.GetPlayOrder)
	router.PUT(options.BaseURL+"/api/order/:gameId", wrapper.SetPlayOrder)
}

type CreateGameRequestObject struct {
}

type CreateGameResponseObject interface {
	VisitCreateGameResponse(w http.ResponseWriter) error
}

type CreateGame201JSONResponse GameCreatedResponse

func (response CreateGame201JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateGame400JSONResponse BadRequestResponse

func (response CreateGame400JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateGame401JSONResponse UnauthorizedResponse

func (response CreateGame401JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateGame403JSONResponse ForbiddenResponse

func (response CreateGame403JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

type CreateUser201JSONResponse UserToken

func (response CreateUser201JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser400JSONResponse BadRequestResponse

func (response CreateUser400JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser403JSONResponse ForbiddenResponse

func (response CreateUser403JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetAnswersRequestObject struct {
	GameId string `json:"gameId"`
}

type GetAnswersResponseObject interface {
	VisitGetAnswersResponse(w http.ResponseWriter) error
}

type GetAnswers200JSONResponse AnswersResponse

func (response GetAnswers200JSONResponse) VisitGetAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAnswers400JSONResponse BadRequestResponse

func (response GetAnswers400JSONResponse) VisitGetAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAnswers401JSONResponse UnauthorizedResponse

func (response GetAnswers401JSONResponse) VisitGetAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAnswers403JSONResponse ForbiddenResponse

func (response GetAnswers403JSONResponse) VisitGetAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetAnswers404JSONResponse GameNotFoundResponse

func (response GetAnswers404JSONResponse) VisitGetAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SendAnswerRequestObject struct {
	GameId string `json:"gameId"`
	Body   *SendAnswerJSONRequestBody
}

type SendAnswerResponseObject interface {
	VisitSendAnswerResponse(w http.ResponseWriter) error
}

type SendAnswer200JSONResponse AnswerReceivedResponse

func (response SendAnswer200JSONResponse) VisitSendAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SendAnswer400JSONResponse BadRequestResponse

func (response SendAnswer400JSONResponse) VisitSendAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SendAnswer401JSONResponse UnauthorizedResponse

func (response SendAnswer401JSONResponse) VisitSendAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SendAnswer403JSONResponse ForbiddenResponse

func (response SendAnswer403JSONResponse) VisitSendAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type SendAnswer404JSONResponse GameNotFoundResponse

func (response SendAnswer404JSONResponse) VisitSendAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SelectValidAnswersRequestObject struct {
	GameId string `json:"gameId"`
	Body   *SelectValidAnswersJSONRequestBody
}

type SelectValidAnswersResponseObject interface {
	VisitSelectValidAnswersResponse(w http.ResponseWriter) error
}

type SelectValidAnswers200JSONResponse ValidAnswersSelectedResponse

func (response SelectValidAnswers200JSONResponse) VisitSelectValidAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SelectValidAnswers400JSONResponse BadRequestResponse

func (response SelectValidAnswers400JSONResponse) VisitSelectValidAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SelectValidAnswers401JSONResponse UnauthorizedResponse

func (response SelectValidAnswers401JSONResponse) VisitSelectValidAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SelectValidAnswers403JSONResponse ForbiddenResponse

func (response SelectValidAnswers403JSONResponse) VisitSelectValidAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type SelectValidAnswers404JSONResponse GameNotFoundResponse

func (response SelectValidAnswers404JSONResponse) VisitSelectValidAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type FinishGameRequestObject struct {
	GameId string `json:"gameId"`
}

type FinishGameResponseObject interface {
	VisitFinishGameResponse(w http.ResponseWriter) error
}

type FinishGame200JSONResponse GameFinishedResponse

func (response FinishGame200JSONResponse) VisitFinishGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FinishGame400JSONResponse BadRequestResponse

func (response FinishGame400JSONResponse) VisitFinishGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type FinishGame401JSONResponse UnauthorizedResponse

func (response FinishGame401JSONResponse) VisitFinishGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type FinishGame403JSONResponse ForbiddenResponse

func (response FinishGame403JSONResponse) VisitFinishGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type FinishGame404JSONResponse GameNotFoundResponse

func (response FinishGame404JSONResponse) VisitFinishGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type NextRoundRequestObject struct {
	GameId string `json:"gameId"`
}

type NextRoundResponseObject interface {
	VisitNextRoundResponse(w http.ResponseWriter) error
}

type NextRound200JSONResponse NextRoundResponse

func (response NextRound200JSONResponse) VisitNextRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type NextRound400JSONResponse BadRequestResponse

func (response NextRound400JSONResponse) VisitNextRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type NextRound401JSONResponse UnauthorizedResponse

func (response NextRound401JSONResponse) VisitNextRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type NextRound403JSONResponse ForbiddenResponse

func (response NextRound403JSONResponse) VisitNextRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type NextRound404JSONResponse GameNotFoundResponse

func (response NextRound404JSONResponse) VisitNextRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PingGameRequestObject struct {
	GameId string `json:"gameId"`
}

type PingGameResponseObject interface {
	VisitPingGameResponse(w http.ResponseWriter) error
}

type PingGame200JSONResponse PingResponse

func (response PingGame200JSONResponse) VisitPingGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PingGame400JSONResponse BadRequestResponse

func (response PingGame400JSONResponse) VisitPingGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PingGame401JSONResponse UnauthorizedResponse

func (response PingGame401JSONResponse) VisitPingGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PingGame403JSONResponse ForbiddenResponse

func (response PingGame403JSONResponse) VisitPingGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PingGame404JSONResponse GameNotFoundResponse

func (response PingGame404JSONResponse) VisitPingGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type KickPlayerRequestObject struct {
	GameId   string `json:"gameId"`
	UserUUID UUID   `json:"userUUID"`
}

type KickPlayerResponseObject interface {
	VisitKickPlayerResponse(w http.ResponseWriter) error
}

type KickPlayer200JSONResponse PlayerKickedResponse

func (response KickPlayer200JSONResponse) VisitKickPlayerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type KickPlayer400JSONResponse BadRequestResponse

func (response KickPlayer400JSONResponse) VisitKickPlayerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type KickPlayer401JSONResponse UnauthorizedResponse

func (response KickPlayer401JSONResponse) VisitKickPlayerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type KickPlayer403JSONResponse ForbiddenResponse

func (response KickPlayer403JSONResponse) VisitKickPlayerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type KickPlayer404JSONResponse GameNotFoundResponse

func (response KickPlayer404JSONResponse) VisitKickPlayerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RevealVotesRequestObject struct {
	GameId string `json:"gameId"`
}

type RevealVotesResponseObject interface {
	VisitRevealVotesResponse(w http.ResponseWriter) error
}

type RevealVotes200JSONResponse RevealVotesResponse

func (response RevealVotes200JSONResponse) VisitRevealVotesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RevealVotes400JSONResponse BadRequestResponse

func (response RevealVotes400JSONResponse) VisitRevealVotesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RevealVotes401JSONResponse UnauthorizedResponse

func (response RevealVotes401JSONResponse) VisitRevealVotesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RevealVotes403JSONResponse ForbiddenResponse

func (response RevealVotes403JSONResponse) VisitRevealVotesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type RevealVotes404JSONResponse GameNotFoundResponse

func (response RevealVotes404JSONResponse) VisitRevealVotesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type TriggerRevealRequestObject struct {
	GameId string `json:"gameId"`
}

type TriggerRevealResponseObject interface {
	VisitTriggerRevealResponse(w http.ResponseWriter) error
}

type TriggerReveal200JSONResponse RevealVotesResponse

func (response TriggerReveal200JSONResponse) VisitTriggerRevealResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type TriggerReveal400JSONResponse BadRequestResponse

func (response TriggerReveal400JSONResponse) VisitTriggerRevealResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type TriggerReveal401JSONResponse UnauthorizedResponse

func (response TriggerReveal401JSONResponse) VisitTriggerRevealResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type TriggerReveal403JSONResponse ForbiddenResponse

func (response TriggerReveal403JSONResponse) VisitTriggerRevealResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type TriggerReveal404JSONResponse GameNotFoundResponse

func (response TriggerReveal404JSONResponse) VisitTriggerRevealResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type StartGameRequestObject struct {
	GameId string `json:"gameId"`
}

type StartGameResponseObject interface {
	VisitStartGameResponse(w http.ResponseWriter) error
}

type StartGame200JSONResponse GameStartedResponse

func (response StartGame200JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StartGame400JSONResponse BadRequestResponse

func (response StartGame400JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type StartGame401JSONResponse UnauthorizedResponse

func (response StartGame401JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type StartGame403JSONResponse ForbiddenResponse

func (response StartGame403JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type StartGame404JSONResponse GameNotFoundResponse

func (response StartGame404JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type StartVotingRequestObject struct {
	GameId string `json:"gameId"`
}

type StartVotingResponseObject interface {
	VisitStartVotingResponse(w http.ResponseWriter) error
}

type StartVoting200JSONResponse VotingStartedResponse

func (response StartVoting200JSONResponse) VisitStartVotingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StartVoting400JSONResponse BadRequestResponse

func (response StartVoting400JSONResponse) VisitStartVotingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type StartVoting401JSONResponse UnauthorizedResponse

func (response StartVoting401JSONResponse) VisitStartVotingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type StartVoting403JSONResponse ForbiddenResponse

func (response StartVoting403JSONResponse) VisitStartVotingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type StartVoting404JSONResponse GameNotFoundResponse

func (response StartVoting404JSONResponse) VisitStartVotingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetGameStatusRequestObject struct {
	GameId string `json:"gameId"`
}

type GetGameStatusResponseObject interface {
	VisitGetGameStatusResponse(w http.ResponseWriter) error
}

type GetGameStatus200JSONResponse GameStatusResponse

func (response GetGameStatus200JSONResponse) VisitGetGameStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGameStatus400JSONResponse BadRequestResponse

func (response GetGameStatus400JSONResponse) VisitGetGameStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetGameStatus401JSONResponse UnauthorizedResponse

func (response GetGameStatus401JSONResponse) VisitGetGameStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetGameStatus403JSONResponse ForbiddenResponse

func (response GetGameStatus403JSONResponse) VisitGetGameStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetGameStatus404JSONResponse GameNotFoundResponse

func (response GetGameStatus404JSONResponse) VisitGetGameStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type VoteForAnswerRequestObject struct {
	GameId string `json:"gameId"`
	Body   *VoteForAnswerJSONRequestBody
}

type VoteForAnswerResponseObject interface {
	VisitVoteForAnswerResponse(w http.ResponseWriter) error
}

type VoteForAnswer200JSONResponse VoteRecordedResponse

func (response VoteForAnswer200JSONResponse) VisitVoteForAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type VoteForAnswer400JSONResponse BadRequestResponse

func (response VoteForAnswer400JSONResponse) VisitVoteForAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type VoteForAnswer401JSONResponse UnauthorizedResponse

func (response VoteForAnswer401JSONResponse) VisitVoteForAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type VoteForAnswer403JSONResponse ForbiddenResponse

func (response VoteForAnswer403JSONResponse) VisitVoteForAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type VoteForAnswer404JSONResponse GameNotFoundResponse

func (response VoteForAnswer404JSONResponse) VisitVoteForAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type HealthCheckRequestObject struct {
}

type HealthCheckResponseObject interface {
	VisitHealthCheckResponse(w http.ResponseWriter) error
}

type HealthCheck200JSONResponse HealthStatus

func (response HealthCheck200JSONResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type JoinGameRequestObject struct {
	GameId string `json:"gameId"`
}

type JoinGameResponseObject interface {
	VisitJoinGameResponse(w http.ResponseWriter) error
}

type JoinGame200JSONResponse JoinGameResponse

func (response JoinGame200JSONResponse) VisitJoinGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type JoinGame400JSONResponse BadRequestResponse

func (response JoinGame400JSONResponse) VisitJoinGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type JoinGame401JSONResponse UnauthorizedResponse

func (response JoinGame401JSONResponse) VisitJoinGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type JoinGame403JSONResponse ForbiddenResponse

func (response JoinGame403JSONResponse) VisitJoinGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type JoinGame404JSONResponse GameNotFoundResponse

func (response JoinGame404JSONResponse) VisitJoinGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetPlayOrderRequestObject struct {
	GameId string `json:"gameId"`
}

type GetPlayOrderResponseObject interface {
	VisitGetPlayOrderResponse(w http.ResponseWriter) error
}

type GetPlayOrder200JSONResponse PlayOrderResponse

func (response GetPlayOrder200JSONResponse) VisitGetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPlayOrder400JSONResponse BadRequestResponse

func (response GetPlayOrder400JSONResponse) VisitGetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetPlayOrder401JSONResponse UnauthorizedResponse

func (response GetPlayOrder401JSONResponse) VisitGetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetPlayOrder403JSONResponse ForbiddenResponse

func (response GetPlayOrder403JSONResponse) VisitGetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetPlayOrder404JSONResponse GameNotFoundResponse

func (response GetPlayOrder404JSONResponse) VisitGetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SetPlayOrderRequestObject struct {
	GameId string `json:"gameId"`
	Body   *SetPlayOrderJSONRequestBody
}

type SetPlayOrderResponseObject interface {
	VisitSetPlayOrderResponse(w http.ResponseWriter) error
}

type SetPlayOrder200JSONResponse PlayOrderSetResponse

func (response SetPlayOrder200JSONResponse) VisitSetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SetPlayOrder400JSONResponse BadRequestResponse

func (response SetPlayOrder400JSONResponse) VisitSetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SetPlayOrder401JSONResponse UnauthorizedResponse

func (response SetPlayOrder401JSONResponse) VisitSetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SetPlayOrder403JSONResponse ForbiddenResponse

func (response SetPlayOrder403JSONResponse) VisitSetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type SetPlayOrder404JSONResponse GameNotFoundResponse

func (response SetPlayOrder404JSONResponse) VisitSetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create a game tied to a user
	// (POST /api/create/game)
	CreateGame(ctx context.Context, request CreateGameRequestObject) (CreateGameResponseObject, error)
	// Create a new user
	// (POST /api/create/user)
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)
	// Get the answers for the game
	// (GET /api/game/{gameId}/answers)
	GetAnswers(ctx context.Context, request GetAnswersRequestObject) (GetAnswersResponseObject, error)
	// Send an answer for the game
	// (POST /api/game/{gameId}/answers)
	SendAnswer(ctx context.Context, request SendAnswerRequestObject) (SendAnswerResponseObject, error)
	// Select valid answers for the game
	// (PUT /api/game/{gameId}/answers/selectValids)
	SelectValidAnswers(ctx context.Context, request SelectValidAnswersRequestObject) (SelectValidAnswersResponseObject, error)
	// Finish the game
	// (POST /api/game/{gameId}/finish)
	FinishGame(ctx context.Context, request FinishGameRequestObject) (FinishGameResponseObject, error)
	// Move to the next round in the game
	// (POST /api/game/{gameId}/next)
	NextRound(ctx context.Context, request NextRoundRequestObject) (NextRoundResponseObject, error)
	// Mark a player as still connected
	// (POST /api/game/{gameId}/ping)
	PingGame(ctx context.Context, request PingGameRequestObject) (PingGameResponseObject, error)
	// Kick a player from a game
	// (DELETE /api/game/{gameId}/players/{userUUID})
	KickPlayer(ctx context.Context, request KickPlayerRequestObject) (KickPlayerResponseObject, error)
	// Reveal the answers and votes in the game
	// (GET /api/game/{gameId}/reveal)
	RevealVotes(ctx context.Context, request RevealVotesRequestObject) (RevealVotesResponseObject, error)
	// Reveal votes for the current round
	// (POST /api/game/{gameId}/reveal)
	TriggerReveal(ctx context.Context, request TriggerRevealRequestObject) (TriggerRevealResponseObject, error)
	// Start the game
	// (POST /api/game/{gameId}/start)
	StartGame(ctx context.Context, request StartGameRequestObject) (StartGameResponseObject, error)
	// Start voting for the current round
	// (POST /api/game/{gameId}/startVoting)
	StartVoting(ctx context.Context, request StartVotingRequestObject) (StartVotingResponseObject, error)
	// Get the status of the game
	// (GET /api/game/{gameId}/status)
	GetGameStatus(ctx context.Context, request GetGameStatusRequestObject) (GetGameStatusResponseObject, error)
	// Vote for an answer in the game
	// (POST /api/game/{gameId}/vote)
	VoteForAnswer(ctx context.Context, request VoteForAnswerRequestObject) (VoteForAnswerResponseObject, error)
	// Health check
	// (GET /api/health)
	HealthCheck(ctx context.Context, request HealthCheckRequestObject) (HealthCheckResponseObject, error)
	// Join a game
	// (POST /api/join/{gameId})
	JoinGame(ctx context.Context, request JoinGameRequestObject) (JoinGameResponseObject, error)
	// Gets the play order of the users for the game
	// (GET /api/order/{gameId})
	GetPlayOrder(ctx context.Context, request GetPlayOrderRequestObject) (GetPlayOrderResponseObject, error)
	// Set the play order for the game
	// (PUT /api/order/{gameId})
	SetPlayOrder(ctx context.Context, request SetPlayOrderRequestObject) (SetPlayOrderResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CreateGame operation middleware
func (sh *strictHandler) CreateGame(ctx *gin.Context) {
	var request CreateGameRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateGame(ctx, request.(CreateGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateGame")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateGameResponseObject); ok {
		if err := validResponse.VisitCreateGameResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(ctx *gin.Context) {
	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx, request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		if err := validResponse.VisitCreateUserResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAnswers operation middleware
func (sh *strictHandler) GetAnswers(ctx *gin.Context, gameId string) {
	var request GetAnswersRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAnswers(ctx, request.(GetAnswersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAnswers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAnswersResponseObject); ok {
		if err := validResponse.VisitGetAnswersResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// SendAnswer operation middleware
func (sh *strictHandler) SendAnswer(ctx *gin.Context, gameId string) {
	var request SendAnswerRequestObject

	request.GameId = gameId

	var body SendAnswerJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SendAnswer(ctx, request.(SendAnswerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SendAnswer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SendAnswerResponseObject); ok {
		if err := validResponse.VisitSendAnswerResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// SelectValidAnswers operation middleware
func (sh *strictHandler) SelectValidAnswers(ctx *gin.Context, gameId string) {
	var request SelectValidAnswersRequestObject

	request.GameId = gameId

	var body SelectValidAnswersJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SelectValidAnswers(ctx, request.(SelectValidAnswersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SelectValidAnswers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SelectValidAnswersResponseObject); ok {
		if err := validResponse.VisitSelectValidAnswersResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// FinishGame operation middleware
func (sh *strictHandler) FinishGame(ctx *gin.Context, gameId string) {
	var request FinishGameRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.FinishGame(ctx, request.(FinishGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FinishGame")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(FinishGameResponseObject); ok {
		if err := validResponse.VisitFinishGameResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// NextRound operation middleware
func (sh *strictHandler) NextRound(ctx *gin.Context, gameId string) {
	var request NextRoundRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.NextRound(ctx, request.(NextRoundRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "NextRound")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(NextRoundResponseObject); ok {
		if err := validResponse.VisitNextRoundResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PingGame operation middleware
func (sh *strictHandler) PingGame(ctx *gin.Context, gameId string) {
	var request PingGameRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PingGame(ctx, request.(PingGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PingGame")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PingGameResponseObject); ok {
		if err := validResponse.VisitPingGameResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// KickPlayer operation middleware
func (sh *strictHandler) KickPlayer(ctx *gin.Context, gameId string, userUUID UUID) {
	var request KickPlayerRequestObject

	request.GameId = gameId
	request.UserUUID = userUUID

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.KickPlayer(ctx, request.(KickPlayerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "KickPlayer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(KickPlayerResponseObject); ok {
		if err := validResponse.VisitKickPlayerResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevealVotes operation middleware
func (sh *strictHandler) RevealVotes(ctx *gin.Context, gameId string) {
	var request RevealVotesRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RevealVotes(ctx, request.(RevealVotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevealVotes")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RevealVotesResponseObject); ok {
		if err := validResponse.VisitRevealVotesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerReveal operation middleware
func (sh *strictHandler) TriggerReveal(ctx *gin.Context, gameId string) {
	var request TriggerRevealRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerReveal(ctx, request.(TriggerRevealRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerReveal")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(TriggerRevealResponseObject); ok {
		if err := validResponse.VisitTriggerRevealResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartGame operation middleware
func (sh *strictHandler) StartGame(ctx *gin.Context, gameId string) {
	var request StartGameRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StartGame(ctx, request.(StartGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartGame")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(StartGameResponseObject); ok {
		if err := validResponse.VisitStartGameResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartVoting operation middleware
func (sh *strictHandler) StartVoting(ctx *gin.Context, gameId string) {
	var request StartVotingRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StartVoting(ctx, request.(StartVotingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartVoting")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(StartVotingResponseObject); ok {
		if err := validResponse.VisitStartVotingResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGameStatus operation middleware
func (sh *strictHandler) GetGameStatus(ctx *gin.Context, gameId string) {
	var request GetGameStatusRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetGameStatus(ctx, request.(GetGameStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGameStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetGameStatusResponseObject); ok {
		if err := validResponse.VisitGetGameStatusResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// VoteForAnswer operation middleware
func (sh *strictHandler) VoteForAnswer(ctx *gin.Context, gameId string) {
	var request VoteForAnswerRequestObject

	request.GameId = gameId

	var body VoteForAnswerJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.VoteForAnswer(ctx, request.(VoteForAnswerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VoteForAnswer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(VoteForAnswerResponseObject); ok {
		if err := validResponse.VisitVoteForAnswerResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// HealthCheck operation middleware
func (sh *strictHandler) HealthCheck(ctx *gin.Context) {
	var request HealthCheckRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.HealthCheck(ctx, request.(HealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthCheck")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(HealthCheckResponseObject); ok {
		if err := validResponse.VisitHealthCheckResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// JoinGame operation middleware
func (sh *strictHandler) JoinGame(ctx *gin.Context, gameId string) {
	var request JoinGameRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.JoinGame(ctx, request.(JoinGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "JoinGame")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(JoinGameResponseObject); ok {
		if err := validResponse.VisitJoinGameResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPlayOrder operation middleware
func (sh *strictHandler) GetPlayOrder(ctx *gin.Context, gameId string) {
	var request GetPlayOrderRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPlayOrder(ctx, request.(GetPlayOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPlayOrder")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetPlayOrderResponseObject); ok {
		if err := validResponse.VisitGetPlayOrderResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetPlayOrder operation middleware
func (sh *strictHandler) SetPlayOrder(ctx *gin.Context, gameId string) {
	var request SetPlayOrderRequestObject

	request.GameId = gameId

	var body SetPlayOrderJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SetPlayOrder(ctx, request.(SetPlayOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetPlayOrder")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SetPlayOrderResponseObject); ok {
		if err := validResponse.VisitSetPlayOrderResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcW1PcOhL+KyrvPg7MEDic7LwlnILNIbeCXB5SqS1h99gCW/JK8sBsav77li6+jWWP",
	"h5iQmvITYCR1q9X9qbvV0g/PZ0nKKFApvPkPT/gRJFj/+oqKe+Dqt5SzFLgkoL/j4js84CSNwZt7nyIi",
	"EBEoWSHzbyQZkhGg/2YgJGHUm3hylaqmQnJCQ289sQN9/vzmLzXYPzksvLn3j2nJ0NRyM9Vt1hMvxjcQ",
	"1ym/co2cid3GVe0pTqA+9C2L6H8CBk0K6+ILu7kFX6oxjLiuwAeyhOAKRMqogKb4EhAChxuk8m5aZlbA",
	"O1HVcn6ytWqn/JXI6AuThtqoJw0Ky1w2REIittFRkvwsgHulwDHneNW1AqJd1Yzg+pO3Ft+L+GscWK1r",
	"pw+csw0FeI0DxE2/CUqIEISG+gPhEKAFgTgQ/fTvjAM20mrV/iHM+pzxGxIEQHeaZtFrglYsQwFDlEkU",
	"4SWgFLieN6NK97HvgxBIKrvgIFjG/Z6MXeAEjAw6wCbECbwJ6rz5URYeLnGcweEio33FrcidE0pEtDO4",
	"qa5oYfsikekpL7I4XvUn/Z7Jc5bRYKdV0ISV4Beq6wSlMWAByI/Av9Ooo8SD3vzVn41ribl8nACE6frI",
	"+V9LLDPRvdDvsJC74Vka4xXwM5ZRWeP4pOCCUAmhwQRu96hXJaoEIHxOUg3cc+8CpJYqzZIb4IgtLMYr",
	"zbbb24KzRLcxlJXuFUSPnUTVytV4O2pttvv8dTcj2vqKGcbVijgwXRQd6vM3A6l557pVnZ6Tb4VQ/fG5",
	"/9bwb8CxjFwz+3DpmtLfjFClZjsqtmKoptDolhFq3RgrgB4K/h4e5FW3dTvJv2PaZTIeBIUHifSCPsLE",
	"PhIa7kg8ZS7tcA4e49UHHqiNqo1CmjfprQvFoP2VouhyDXLHyaquiKm+SIB8jIBr7DaIMhoTWqcpeQbF",
	"QDeMxYCpxSwftiPCc4QAHzWoXRL/buctwnRFd7rvI+R7BUvAsfbEh/YHSxe/l5ZdQwy+/IJjEhQOaot/",
	"tqw06g+CdsH6cCIrptfCg9vyGm2GVzkXx9vnlI9fas7Ri2M4+eP0zwN4+a+bg6MXwfEBPvnj9ODkxenp",
	"0cnRnyez2cybeAl+eAs0lJE3Pz6deAmh1T/rGjbxHg5CdmA/ZhkJDjXdyvcDkqSMG3liNYoXEhllN4c+",
	"S6YhY2EMU9VRz+IzxZmMGCf/g90cuGrHCSJUKwxivIgcJLuDnvHqTwPPcyCKYvqTnqMzuCn+1Zefn1PP",
	"qlEbM98Z5/QQhV8o7CCPADyFSFfgqz1pZx6YBOWS6r6PJt2ZcflJOedpAOei/2od/MIkoeHjIh/T99Gx",
	"j3K2wc84katrNTNDSYAOn88YuyOaHlHet2/+nHhmvnmrkgxOySUoWF1PPEIXzOHAE8U2+go3CKdpTHws",
	"bZie4DvQXqaIsGJWOfn3nEgJFEnleAIWBPihokaknvp7dsOCFSICfQS+AF+iA3TBvIm3BC4Mvdnh7PBI",
	"iZilQHFKvLl3fDg7PPYmGlT1ZKc4JVNfx/nT0K5kyozm1bn/SuIYmZYIIwr3JrxdMK45V6qA7omMEEYW",
	"zdXy6Sm+Cby5TahcGK+d23XWPLyYHakfPqMSTKRYEc/0VjBapo63aaYrbaGXZCOWVKybyQRKQiez2WAs",
	"OFJXDg56Zao0Z8MJx7lROnirtjM8HA/GQzPh5WCgaFSzUW/+rWGd376vv088kSUJ5qtCyxA2yimJCeCw",
	"Vk89WFXhsxwEeyp8Tx3X2Kp0XK/uaxasBpNeMyuppZfrjfEu1k9oX6XH4NIbJZ/fxap+B8VtqmWuRqUu",
	"KkWd/jCZ1PW0EkOF0KaUHGTGaeUwRxQwrNWe0XiFyELnhjG3HxOdvmqo7AXIPERS2wLHCUjNwDe78Wn/",
	"u9j2bMZ3U+UmFSHulAr+3tDV4VRm8wDDsV6vigyi5ASWmz7EuDP8xjuDon4yqOPQOAVo8xyKpP/O+1Oe",
	"xHbZrU4/tW9FOI7Zvd3K1KYmgKpQJz/prI20aeXXQG1k9XxWPvxuWD+d7rUTzgYnvnEg71AZ1+n7iCwj",
	"sgyLLNcdcNDtbExFmVM1CcmsG4MKR8P4FAaM1BBoWcu/bIGkzUTuPkFTe5r6F8NUZ1LNoYV9MmgjeI3g",
	"NTR4bYOPFggzdR9bgnjTqIQtTAPkx4ApytKiLEY0EMrUo9iM1X6FRs5ym7ZlddfWjCAwgsCwIHBeN9M2",
	"k6fwILcY/IabIhlK2BKapRwNky9KRfbO4ptFMI4F7FXxMhr+aPjDGv47p3EiQrdiQaoMpxULTNWLQCJi",
	"WRwgH8exKYUFGqSMUIk4hFmMebzSMYzEK2RO7Gu0N0HiI6HhXnoFtTI1xzLbKqKUgwDqA8rSYDxAGxHh",
	"KRAB8zuEbRkvwgIJqU/jGKU6Hm3FA2Px0x95JcPaoEIMEpr48IEqwy8OryOWH16VroOPqa6aq1QU18Hg",
	"kvh3xi6eBQ4mTipFHUcXnR7FI08KNq5qxnbQcZUujrgz4s6wuKPUscQdfZ0AdzogXBfG9j6uNc2hzHFg",
	"GiB9iavT46iU3+6d0+EqLe44qS0FVshyxIQRE54QE4yC1k5t3Vbbenx7lnEONA9r7KEJ49bDUC4H4yjB",
	"NMNxvLJ6LZCKVpbW5Otw8ImTMARuGBsBYQSEERCeARCM0uWHFH7Vxtu8BV2ovCV3qduUAUi1vraJBLps",
	"em9PKDaLwtuW0ln/Pdr9aPcDH1LWLLPTxs3FhHZL7+UR6JGEJrg0Fx3SCAsoPAU3GljS+4YH7msirgKG",
	"jjshIyaMmPAUmGDNc1dfwN6e75U5EI3b/4hQP84CRVg7B9oT3lLqXb71sK8OQ/UZC8dyOx5RGEFhBIWn",
	"KfIWDmVzg4GKJXrVNJTl36qLRpyy5rMrhaji6XPG968IvHpd9lfXVrouCbtdkrYbwSP4jOAzLPh86caF",
	"AoAi/YZPxf+o44V54ucsAv/Oe0ITqr0k5BDGh8uNm3Smg3lkq5zMLSO0QNMdgVT1VcKCByK0G+fEz/wJ",
	"o73zmxpvM7Vd7Nx8e2mErhG6hoWuv7UlbuCUfhaqZtu94qW0fFLK+l8mSOq8k3JRedJn/6q7Gu+EtVRb",
	"WLEVd2JHSx8tffgISfQ30/Wk40qasMFWZaQt985+Bxt/ihtnzefIfnE85HwBsBtkGs/9jVgzYs3Qd8u6",
	"AWJtBuTLHAPq1N8yH8cogCXELE2ASmTaehMv47E39yIp0/l0Gqt2ERNy/nL2cuatv6//HwAA//+eJ71n",
	"/V4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
