// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a game tied to a user
	// (POST /api/create/game)
	CreateGame(c *gin.Context)
	// Create a new user
	// (POST /api/create/user)
	CreateUser(c *gin.Context)
	// Get the answers for the game
	// (GET /api/game/{gameId}/answers)
	GetAnswers(c *gin.Context, gameId string)
	// Send an answer for the game
	// (POST /api/game/{gameId}/answers)
	SendAnswer(c *gin.Context, gameId string)
	// Finish the game
	// (POST /api/game/{gameId}/finish)
	FinishGame(c *gin.Context, gameId string)
	// Leave a game
	// (POST /api/game/{gameId}/leave)
	LeaveGame(c *gin.Context, gameId string)
	// Move to the next round in the game
	// (POST /api/game/{gameId}/next)
	NextRound(c *gin.Context, gameId string)
	// Kick a player from a game
	// (DELETE /api/game/{gameId}/players/{userUUID})
	KickPlayer(c *gin.Context, gameId string, userUUID UUID)
	// Reveal the answers and votes in the game
	// (GET /api/game/{gameId}/reveal)
	RevealVotes(c *gin.Context, gameId string)
	// Reveal votes for the current round
	// (POST /api/game/{gameId}/reveal)
	TriggerReveal(c *gin.Context, gameId string)
	// Start the game
	// (POST /api/game/{gameId}/start)
	StartGame(c *gin.Context, gameId string)
	// Start voting for the current round
	// (POST /api/game/{gameId}/startVoting)
	StartVoting(c *gin.Context, gameId string)
	// Get the status of the game
	// (GET /api/game/{gameId}/status)
	GetGameStatus(c *gin.Context, gameId string)
	// Vote for an answer in the game
	// (POST /api/game/{gameId}/vote)
	VoteForAnswer(c *gin.Context, gameId string)
	// Health check
	// (GET /api/health)
	HealthCheck(c *gin.Context)
	// Join a game
	// (POST /api/join/{gameId})
	JoinGame(c *gin.Context, gameId string)
	// Log out the current user
	// (POST /api/logout)
	Logout(c *gin.Context)
	// Gets the play order of the users for the game
	// (GET /api/order/{gameId})
	GetPlayOrder(c *gin.Context, gameId string)
	// Set the play order for the game
	// (PUT /api/order/{gameId})
	SetPlayOrder(c *gin.Context, gameId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateGame operation middleware
func (siw *ServerInterfaceWrapper) CreateGame(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateGame(c)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateUser(c)
}

// GetAnswers operation middleware
func (siw *ServerInterfaceWrapper) GetAnswers(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAnswers(c, gameId)
}

// SendAnswer operation middleware
func (siw *ServerInterfaceWrapper) SendAnswer(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SendAnswer(c, gameId)
}

// FinishGame operation middleware
func (siw *ServerInterfaceWrapper) FinishGame(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.FinishGame(c, gameId)
}

// LeaveGame operation middleware
func (siw *ServerInterfaceWrapper) LeaveGame(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LeaveGame(c, gameId)
}

// NextRound operation middleware
func (siw *ServerInterfaceWrapper) NextRound(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.NextRound(c, gameId)
}

// KickPlayer operation middleware
func (siw *ServerInterfaceWrapper) KickPlayer(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "userUUID" -------------
	var userUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userUUID", c.Param("userUUID"), &userUUID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userUUID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.KickPlayer(c, gameId, userUUID)
}

// RevealVotes operation middleware
func (siw *ServerInterfaceWrapper) RevealVotes(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevealVotes(c, gameId)
}

// TriggerReveal operation middleware
func (siw *ServerInterfaceWrapper) TriggerReveal(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TriggerReveal(c, gameId)
}

// StartGame operation middleware
func (siw *ServerInterfaceWrapper) StartGame(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartGame(c, gameId)
}

// StartVoting operation middleware
func (siw *ServerInterfaceWrapper) StartVoting(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartVoting(c, gameId)
}

// GetGameStatus operation middleware
func (siw *ServerInterfaceWrapper) GetGameStatus(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGameStatus(c, gameId)
}

// VoteForAnswer operation middleware
func (siw *ServerInterfaceWrapper) VoteForAnswer(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.VoteForAnswer(c, gameId)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HealthCheck(c)
}

// JoinGame operation middleware
func (siw *ServerInterfaceWrapper) JoinGame(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.JoinGame(c, gameId)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// GetPlayOrder operation middleware
func (siw *ServerInterfaceWrapper) GetPlayOrder(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPlayOrder(c, gameId)
}

// SetPlayOrder operation middleware
func (siw *ServerInterfaceWrapper) SetPlayOrder(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetPlayOrder(c, gameId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/create/game", wrapper.CreateGame)
	router.POST(options.BaseURL+"/api/create/user", wrapper.CreateUser)
	router.GET(options.BaseURL+"/api/game/:gameId/answers", wrapper.GetAnswers)
	router.POST(options.BaseURL+"/api/game/:gameId/answers", wrapper.SendAnswer)
	router.POST(options.BaseURL+"/api/game/:gameId/finish", wrapper.FinishGame)
	router.POST(options.BaseURL+"/api/game/:gameId/leave", wrapper.LeaveGame)
	router.POST(options.BaseURL+"/api/game/:gameId/next", wrapper.NextRound)
	router.DELETE(options.BaseURL+"/api/game/:gameId/players/:userUUID", wrapper.KickPlayer)
	router.GET(options.BaseURL+"/api/game/:gameId/reveal", wrapper.RevealVotes)
	router.POST(options.BaseURL+"/api/game/:gameId/reveal", wrapper.TriggerReveal)
	router.POST(options.BaseURL+"/api/game/:gameId/start", wrapper.StartGame)
	router.POST(options.BaseURL+"/api/game/:gameId/startVoting", wrapper.StartVoting)
	router.GET(options.BaseURL+"/api/game/:gameId/status", wrapper.GetGameStatus)
	router.POST(options.BaseURL+"/api/game/:gameId/vote", wrapper.VoteForAnswer)
	router.GET(options.BaseURL+"/api/health", wrapper.HealthCheck)
	router.POST(options.BaseURL+"/api/join/:gameId", wrapper.JoinGame)
	router.POST(options.BaseURL+"/api/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/api/order/:gameId", wrapper.GetPlayOrder)
	router.PUT(options.BaseURL+"/api/order/:gameId", wrapper.SetPlayOrder)
}

type CreateGameRequestObject struct {
}

type CreateGameResponseObject interface {
	VisitCreateGameResponse(w http.ResponseWriter) error
}

type CreateGame201JSONResponse GameCreatedResponse

func (response CreateGame201JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateGame400JSONResponse BadRequestResponse

func (response CreateGame400JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateGame401JSONResponse UnauthorizedResponse

func (response CreateGame401JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateGame403JSONResponse ForbiddenResponse

func (response CreateGame403JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

type CreateUser201JSONResponse UserToken

func (response CreateUser201JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser400JSONResponse BadRequestResponse

func (response CreateUser400JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser403JSONResponse ForbiddenResponse

func (response CreateUser403JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetAnswersRequestObject struct {
	GameId string `json:"gameId"`
}

type GetAnswersResponseObject interface {
	VisitGetAnswersResponse(w http.ResponseWriter) error
}

type GetAnswers200JSONResponse AnswersResponse

func (response GetAnswers200JSONResponse) VisitGetAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAnswers400JSONResponse BadRequestResponse

func (response GetAnswers400JSONResponse) VisitGetAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAnswers401JSONResponse UnauthorizedResponse

func (response GetAnswers401JSONResponse) VisitGetAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAnswers403JSONResponse ForbiddenResponse

func (response GetAnswers403JSONResponse) VisitGetAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetAnswers404JSONResponse GameNotFoundResponse

func (response GetAnswers404JSONResponse) VisitGetAnswersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SendAnswerRequestObject struct {
	GameId string `json:"gameId"`
	Body   *SendAnswerJSONRequestBody
}

type SendAnswerResponseObject interface {
	VisitSendAnswerResponse(w http.ResponseWriter) error
}

type SendAnswer200JSONResponse AnswerReceivedResponse

func (response SendAnswer200JSONResponse) VisitSendAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SendAnswer400JSONResponse BadRequestResponse

func (response SendAnswer400JSONResponse) VisitSendAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SendAnswer401JSONResponse UnauthorizedResponse

func (response SendAnswer401JSONResponse) VisitSendAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SendAnswer403JSONResponse ForbiddenResponse

func (response SendAnswer403JSONResponse) VisitSendAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type SendAnswer404JSONResponse GameNotFoundResponse

func (response SendAnswer404JSONResponse) VisitSendAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type FinishGameRequestObject struct {
	GameId string `json:"gameId"`
}

type FinishGameResponseObject interface {
	VisitFinishGameResponse(w http.ResponseWriter) error
}

type FinishGame200JSONResponse GameFinishedResponse

func (response FinishGame200JSONResponse) VisitFinishGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FinishGame400JSONResponse BadRequestResponse

func (response FinishGame400JSONResponse) VisitFinishGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type FinishGame401JSONResponse UnauthorizedResponse

func (response FinishGame401JSONResponse) VisitFinishGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type FinishGame403JSONResponse ForbiddenResponse

func (response FinishGame403JSONResponse) VisitFinishGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type FinishGame404JSONResponse GameNotFoundResponse

func (response FinishGame404JSONResponse) VisitFinishGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type LeaveGameRequestObject struct {
	GameId string `json:"gameId"`
}

type LeaveGameResponseObject interface {
	VisitLeaveGameResponse(w http.ResponseWriter) error
}

type LeaveGame200JSONResponse GameLeftResponse

func (response LeaveGame200JSONResponse) VisitLeaveGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LeaveGame400JSONResponse BadRequestResponse

func (response LeaveGame400JSONResponse) VisitLeaveGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type LeaveGame401JSONResponse UnauthorizedResponse

func (response LeaveGame401JSONResponse) VisitLeaveGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LeaveGame403JSONResponse ForbiddenResponse

func (response LeaveGame403JSONResponse) VisitLeaveGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type LeaveGame404JSONResponse GameNotFoundResponse

func (response LeaveGame404JSONResponse) VisitLeaveGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type NextRoundRequestObject struct {
	GameId string `json:"gameId"`
}

type NextRoundResponseObject interface {
	VisitNextRoundResponse(w http.ResponseWriter) error
}

type NextRound200JSONResponse NextRoundResponse

func (response NextRound200JSONResponse) VisitNextRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type NextRound400JSONResponse BadRequestResponse

func (response NextRound400JSONResponse) VisitNextRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type NextRound401JSONResponse UnauthorizedResponse

func (response NextRound401JSONResponse) VisitNextRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type NextRound403JSONResponse ForbiddenResponse

func (response NextRound403JSONResponse) VisitNextRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type NextRound404JSONResponse GameNotFoundResponse

func (response NextRound404JSONResponse) VisitNextRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type KickPlayerRequestObject struct {
	GameId   string `json:"gameId"`
	UserUUID UUID   `json:"userUUID"`
}

type KickPlayerResponseObject interface {
	VisitKickPlayerResponse(w http.ResponseWriter) error
}

type KickPlayer200JSONResponse PlayerKickedResponse

func (response KickPlayer200JSONResponse) VisitKickPlayerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type KickPlayer400JSONResponse BadRequestResponse

func (response KickPlayer400JSONResponse) VisitKickPlayerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type KickPlayer401JSONResponse UnauthorizedResponse

func (response KickPlayer401JSONResponse) VisitKickPlayerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type KickPlayer403JSONResponse ForbiddenResponse

func (response KickPlayer403JSONResponse) VisitKickPlayerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type KickPlayer404JSONResponse GameNotFoundResponse

func (response KickPlayer404JSONResponse) VisitKickPlayerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RevealVotesRequestObject struct {
	GameId string `json:"gameId"`
}

type RevealVotesResponseObject interface {
	VisitRevealVotesResponse(w http.ResponseWriter) error
}

type RevealVotes200JSONResponse RevealVotesResponse

func (response RevealVotes200JSONResponse) VisitRevealVotesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RevealVotes400JSONResponse BadRequestResponse

func (response RevealVotes400JSONResponse) VisitRevealVotesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RevealVotes401JSONResponse UnauthorizedResponse

func (response RevealVotes401JSONResponse) VisitRevealVotesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RevealVotes403JSONResponse ForbiddenResponse

func (response RevealVotes403JSONResponse) VisitRevealVotesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type RevealVotes404JSONResponse GameNotFoundResponse

func (response RevealVotes404JSONResponse) VisitRevealVotesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type TriggerRevealRequestObject struct {
	GameId string `json:"gameId"`
}

type TriggerRevealResponseObject interface {
	VisitTriggerRevealResponse(w http.ResponseWriter) error
}

type TriggerReveal200JSONResponse RevealVotesResponse

func (response TriggerReveal200JSONResponse) VisitTriggerRevealResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type TriggerReveal400JSONResponse BadRequestResponse

func (response TriggerReveal400JSONResponse) VisitTriggerRevealResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type TriggerReveal401JSONResponse UnauthorizedResponse

func (response TriggerReveal401JSONResponse) VisitTriggerRevealResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type TriggerReveal403JSONResponse ForbiddenResponse

func (response TriggerReveal403JSONResponse) VisitTriggerRevealResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type TriggerReveal404JSONResponse GameNotFoundResponse

func (response TriggerReveal404JSONResponse) VisitTriggerRevealResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type StartGameRequestObject struct {
	GameId string `json:"gameId"`
}

type StartGameResponseObject interface {
	VisitStartGameResponse(w http.ResponseWriter) error
}

type StartGame200JSONResponse GameStartedResponse

func (response StartGame200JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StartGame400JSONResponse BadRequestResponse

func (response StartGame400JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type StartGame401JSONResponse UnauthorizedResponse

func (response StartGame401JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type StartGame403JSONResponse ForbiddenResponse

func (response StartGame403JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type StartGame404JSONResponse GameNotFoundResponse

func (response StartGame404JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type StartVotingRequestObject struct {
	GameId string `json:"gameId"`
}

type StartVotingResponseObject interface {
	VisitStartVotingResponse(w http.ResponseWriter) error
}

type StartVoting200JSONResponse VotingStartedResponse

func (response StartVoting200JSONResponse) VisitStartVotingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StartVoting400JSONResponse BadRequestResponse

func (response StartVoting400JSONResponse) VisitStartVotingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type StartVoting401JSONResponse UnauthorizedResponse

func (response StartVoting401JSONResponse) VisitStartVotingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type StartVoting403JSONResponse ForbiddenResponse

func (response StartVoting403JSONResponse) VisitStartVotingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type StartVoting404JSONResponse GameNotFoundResponse

func (response StartVoting404JSONResponse) VisitStartVotingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetGameStatusRequestObject struct {
	GameId string `json:"gameId"`
}

type GetGameStatusResponseObject interface {
	VisitGetGameStatusResponse(w http.ResponseWriter) error
}

type GetGameStatus200JSONResponse GameStatusResponse

func (response GetGameStatus200JSONResponse) VisitGetGameStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGameStatus400JSONResponse BadRequestResponse

func (response GetGameStatus400JSONResponse) VisitGetGameStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetGameStatus401JSONResponse UnauthorizedResponse

func (response GetGameStatus401JSONResponse) VisitGetGameStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetGameStatus403JSONResponse ForbiddenResponse

func (response GetGameStatus403JSONResponse) VisitGetGameStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetGameStatus404JSONResponse GameNotFoundResponse

func (response GetGameStatus404JSONResponse) VisitGetGameStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type VoteForAnswerRequestObject struct {
	GameId string `json:"gameId"`
	Body   *VoteForAnswerJSONRequestBody
}

type VoteForAnswerResponseObject interface {
	VisitVoteForAnswerResponse(w http.ResponseWriter) error
}

type VoteForAnswer200JSONResponse VoteRecordedResponse

func (response VoteForAnswer200JSONResponse) VisitVoteForAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type VoteForAnswer400JSONResponse BadRequestResponse

func (response VoteForAnswer400JSONResponse) VisitVoteForAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type VoteForAnswer401JSONResponse UnauthorizedResponse

func (response VoteForAnswer401JSONResponse) VisitVoteForAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type VoteForAnswer403JSONResponse ForbiddenResponse

func (response VoteForAnswer403JSONResponse) VisitVoteForAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type VoteForAnswer404JSONResponse GameNotFoundResponse

func (response VoteForAnswer404JSONResponse) VisitVoteForAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type HealthCheckRequestObject struct {
}

type HealthCheckResponseObject interface {
	VisitHealthCheckResponse(w http.ResponseWriter) error
}

type HealthCheck200JSONResponse HealthStatus

func (response HealthCheck200JSONResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type JoinGameRequestObject struct {
	GameId string `json:"gameId"`
}

type JoinGameResponseObject interface {
	VisitJoinGameResponse(w http.ResponseWriter) error
}

type JoinGame200JSONResponse JoinGameResponse

func (response JoinGame200JSONResponse) VisitJoinGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type JoinGame400JSONResponse BadRequestResponse

func (response JoinGame400JSONResponse) VisitJoinGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type JoinGame401JSONResponse UnauthorizedResponse

func (response JoinGame401JSONResponse) VisitJoinGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type JoinGame403JSONResponse ForbiddenResponse

func (response JoinGame403JSONResponse) VisitJoinGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type JoinGame404JSONResponse GameNotFoundResponse

func (response JoinGame404JSONResponse) VisitJoinGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout200JSONResponse LogoutResponse

func (response Logout200JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPlayOrderRequestObject struct {
	GameId string `json:"gameId"`
}

type GetPlayOrderResponseObject interface {
	VisitGetPlayOrderResponse(w http.ResponseWriter) error
}

type GetPlayOrder200JSONResponse PlayOrderResponse

func (response GetPlayOrder200JSONResponse) VisitGetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPlayOrder400JSONResponse BadRequestResponse

func (response GetPlayOrder400JSONResponse) VisitGetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetPlayOrder401JSONResponse UnauthorizedResponse

func (response GetPlayOrder401JSONResponse) VisitGetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetPlayOrder403JSONResponse ForbiddenResponse

func (response GetPlayOrder403JSONResponse) VisitGetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetPlayOrder404JSONResponse GameNotFoundResponse

func (response GetPlayOrder404JSONResponse) VisitGetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SetPlayOrderRequestObject struct {
	GameId string `json:"gameId"`
	Body   *SetPlayOrderJSONRequestBody
}

type SetPlayOrderResponseObject interface {
	VisitSetPlayOrderResponse(w http.ResponseWriter) error
}

type SetPlayOrder200JSONResponse PlayOrderSetResponse

func (response SetPlayOrder200JSONResponse) VisitSetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SetPlayOrder400JSONResponse BadRequestResponse

func (response SetPlayOrder400JSONResponse) VisitSetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SetPlayOrder401JSONResponse UnauthorizedResponse

func (response SetPlayOrder401JSONResponse) VisitSetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SetPlayOrder403JSONResponse ForbiddenResponse

func (response SetPlayOrder403JSONResponse) VisitSetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type SetPlayOrder404JSONResponse GameNotFoundResponse

func (response SetPlayOrder404JSONResponse) VisitSetPlayOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create a game tied to a user
	// (POST /api/create/game)
	CreateGame(ctx context.Context, request CreateGameRequestObject) (CreateGameResponseObject, error)
	// Create a new user
	// (POST /api/create/user)
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)
	// Get the answers for the game
	// (GET /api/game/{gameId}/answers)
	GetAnswers(ctx context.Context, request GetAnswersRequestObject) (GetAnswersResponseObject, error)
	// Send an answer for the game
	// (POST /api/game/{gameId}/answers)
	SendAnswer(ctx context.Context, request SendAnswerRequestObject) (SendAnswerResponseObject, error)
	// Finish the game
	// (POST /api/game/{gameId}/finish)
	FinishGame(ctx context.Context, request FinishGameRequestObject) (FinishGameResponseObject, error)
	// Leave a game
	// (POST /api/game/{gameId}/leave)
	LeaveGame(ctx context.Context, request LeaveGameRequestObject) (LeaveGameResponseObject, error)
	// Move to the next round in the game
	// (POST /api/game/{gameId}/next)
	NextRound(ctx context.Context, request NextRoundRequestObject) (NextRoundResponseObject, error)
	// Kick a player from a game
	// (DELETE /api/game/{gameId}/players/{userUUID})
	KickPlayer(ctx context.Context, request KickPlayerRequestObject) (KickPlayerResponseObject, error)
	// Reveal the answers and votes in the game
	// (GET /api/game/{gameId}/reveal)
	RevealVotes(ctx context.Context, request RevealVotesRequestObject) (RevealVotesResponseObject, error)
	// Reveal votes for the current round
	// (POST /api/game/{gameId}/reveal)
	TriggerReveal(ctx context.Context, request TriggerRevealRequestObject) (TriggerRevealResponseObject, error)
	// Start the game
	// (POST /api/game/{gameId}/start)
	StartGame(ctx context.Context, request StartGameRequestObject) (StartGameResponseObject, error)
	// Start voting for the current round
	// (POST /api/game/{gameId}/startVoting)
	StartVoting(ctx context.Context, request StartVotingRequestObject) (StartVotingResponseObject, error)
	// Get the status of the game
	// (GET /api/game/{gameId}/status)
	GetGameStatus(ctx context.Context, request GetGameStatusRequestObject) (GetGameStatusResponseObject, error)
	// Vote for an answer in the game
	// (POST /api/game/{gameId}/vote)
	VoteForAnswer(ctx context.Context, request VoteForAnswerRequestObject) (VoteForAnswerResponseObject, error)
	// Health check
	// (GET /api/health)
	HealthCheck(ctx context.Context, request HealthCheckRequestObject) (HealthCheckResponseObject, error)
	// Join a game
	// (POST /api/join/{gameId})
	JoinGame(ctx context.Context, request JoinGameRequestObject) (JoinGameResponseObject, error)
	// Log out the current user
	// (POST /api/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Gets the play order of the users for the game
	// (GET /api/order/{gameId})
	GetPlayOrder(ctx context.Context, request GetPlayOrderRequestObject) (GetPlayOrderResponseObject, error)
	// Set the play order for the game
	// (PUT /api/order/{gameId})
	SetPlayOrder(ctx context.Context, request SetPlayOrderRequestObject) (SetPlayOrderResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CreateGame operation middleware
func (sh *strictHandler) CreateGame(ctx *gin.Context) {
	var request CreateGameRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateGame(ctx, request.(CreateGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateGame")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateGameResponseObject); ok {
		if err := validResponse.VisitCreateGameResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(ctx *gin.Context) {
	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx, request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		if err := validResponse.VisitCreateUserResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAnswers operation middleware
func (sh *strictHandler) GetAnswers(ctx *gin.Context, gameId string) {
	var request GetAnswersRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAnswers(ctx, request.(GetAnswersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAnswers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAnswersResponseObject); ok {
		if err := validResponse.VisitGetAnswersResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// SendAnswer operation middleware
func (sh *strictHandler) SendAnswer(ctx *gin.Context, gameId string) {
	var request SendAnswerRequestObject

	request.GameId = gameId

	var body SendAnswerJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SendAnswer(ctx, request.(SendAnswerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SendAnswer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SendAnswerResponseObject); ok {
		if err := validResponse.VisitSendAnswerResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// FinishGame operation middleware
func (sh *strictHandler) FinishGame(ctx *gin.Context, gameId string) {
	var request FinishGameRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.FinishGame(ctx, request.(FinishGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FinishGame")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(FinishGameResponseObject); ok {
		if err := validResponse.VisitFinishGameResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// LeaveGame operation middleware
func (sh *strictHandler) LeaveGame(ctx *gin.Context, gameId string) {
	var request LeaveGameRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LeaveGame(ctx, request.(LeaveGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LeaveGame")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(LeaveGameResponseObject); ok {
		if err := validResponse.VisitLeaveGameResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// NextRound operation middleware
func (sh *strictHandler) NextRound(ctx *gin.Context, gameId string) {
	var request NextRoundRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.NextRound(ctx, request.(NextRoundRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "NextRound")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(NextRoundResponseObject); ok {
		if err := validResponse.VisitNextRoundResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// KickPlayer operation middleware
func (sh *strictHandler) KickPlayer(ctx *gin.Context, gameId string, userUUID UUID) {
	var request KickPlayerRequestObject

	request.GameId = gameId
	request.UserUUID = userUUID

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.KickPlayer(ctx, request.(KickPlayerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "KickPlayer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(KickPlayerResponseObject); ok {
		if err := validResponse.VisitKickPlayerResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevealVotes operation middleware
func (sh *strictHandler) RevealVotes(ctx *gin.Context, gameId string) {
	var request RevealVotesRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RevealVotes(ctx, request.(RevealVotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevealVotes")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RevealVotesResponseObject); ok {
		if err := validResponse.VisitRevealVotesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerReveal operation middleware
func (sh *strictHandler) TriggerReveal(ctx *gin.Context, gameId string) {
	var request TriggerRevealRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerReveal(ctx, request.(TriggerRevealRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerReveal")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(TriggerRevealResponseObject); ok {
		if err := validResponse.VisitTriggerRevealResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartGame operation middleware
func (sh *strictHandler) StartGame(ctx *gin.Context, gameId string) {
	var request StartGameRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StartGame(ctx, request.(StartGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartGame")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(StartGameResponseObject); ok {
		if err := validResponse.VisitStartGameResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartVoting operation middleware
func (sh *strictHandler) StartVoting(ctx *gin.Context, gameId string) {
	var request StartVotingRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StartVoting(ctx, request.(StartVotingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartVoting")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(StartVotingResponseObject); ok {
		if err := validResponse.VisitStartVotingResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGameStatus operation middleware
func (sh *strictHandler) GetGameStatus(ctx *gin.Context, gameId string) {
	var request GetGameStatusRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetGameStatus(ctx, request.(GetGameStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGameStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetGameStatusResponseObject); ok {
		if err := validResponse.VisitGetGameStatusResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// VoteForAnswer operation middleware
func (sh *strictHandler) VoteForAnswer(ctx *gin.Context, gameId string) {
	var request VoteForAnswerRequestObject

	request.GameId = gameId

	var body VoteForAnswerJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.VoteForAnswer(ctx, request.(VoteForAnswerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VoteForAnswer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(VoteForAnswerResponseObject); ok {
		if err := validResponse.VisitVoteForAnswerResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// HealthCheck operation middleware
func (sh *strictHandler) HealthCheck(ctx *gin.Context) {
	var request HealthCheckRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.HealthCheck(ctx, request.(HealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthCheck")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(HealthCheckResponseObject); ok {
		if err := validResponse.VisitHealthCheckResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// JoinGame operation middleware
func (sh *strictHandler) JoinGame(ctx *gin.Context, gameId string) {
	var request JoinGameRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.JoinGame(ctx, request.(JoinGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "JoinGame")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(JoinGameResponseObject); ok {
		if err := validResponse.VisitJoinGameResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx *gin.Context) {
	var request LogoutRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPlayOrder operation middleware
func (sh *strictHandler) GetPlayOrder(ctx *gin.Context, gameId string) {
	var request GetPlayOrderRequestObject

	request.GameId = gameId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPlayOrder(ctx, request.(GetPlayOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPlayOrder")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetPlayOrderResponseObject); ok {
		if err := validResponse.VisitGetPlayOrderResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetPlayOrder operation middleware
func (sh *strictHandler) SetPlayOrder(ctx *gin.Context, gameId string) {
	var request SetPlayOrderRequestObject

	request.GameId = gameId

	var body SetPlayOrderJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SetPlayOrder(ctx, request.(SetPlayOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetPlayOrder")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SetPlayOrderResponseObject); ok {
		if err := validResponse.VisitSetPlayOrderResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc23LbONJ+FRT//5KW5MN4srpLPGuvx86h7BwuplJbENkiYZMAFwBla1N69y0AFA8i",
	"SFEKPU6peJWYAtCNRveHRncDPxyPxQmjQKVwpj8c4YUQY/3ft1Q8AVf/SzhLgEsC+jvOv8MzjpMInKnz",
	"OSQCEYHiJTI/I8mQDAH9JwUhCaOO68hlopoKyQkNnJWbDfTly/UfarD/5zB3ps7/jQuGxhk3Y91m5ToR",
	"nkFUpfzWNnIqdhtXtac4hurQDyyk//YZ1Cms8i9s9gCeVGMYcd2BB2QB/h2IhFEBdfHFIAQONkitu2mZ",
	"ZQLeiaqW84utVTPlb0SGX5k01AY9qVFYrGVDJMRiGx0lyS8CuFMIHHOOl20rIJpVzQiuO/nM4jsRf4f9",
	"TOua6QPnbEMB3mEfcdPPRTERgtBAfyAcfDQnEPmim/5dcMBGWo3a34dZXzI+I74PdKdp5r1ctGQp8hmi",
	"TKIQLwAlwPW8GVW6jz0PhEBS2QUHwVLudWTsCsdgZNACNgGO4dqv8uaFaTBa4CiF0TylXcWtyF0SSkS4",
	"M7iprmie9UUi1VOep1G07E76FuZyR7Kqi8YWJYQ9yX5g8pKl1N9p8fV81XrPVVcXJRFgAcgLwXssGLr+",
	"ozsb9xJzuZ/chem65/zvJZapaNev91jI3WA0ifAS+AVLqaxwfJZzQaiEwEARz7bGtwWY+SA8ThK9X0yd",
	"KzDLTNN4Bhyxeba1KIPKdtU5Z7FuYygrlc+JnrYRzbe2bSQ1zm8QhIgEZBaB/rFK9MRKVKlLRSDHjc12",
	"F7ruZtazqiZGWkoNLPuXyDtUJWAGUjNfK3R5ela+FRp334u6b4P/AhzJ0Dazjze2Kf3JCFW6vaM1KYYq",
	"VoQeGKGZy5YJoINV3bKApTtDGQsC8BFL5R52/AGe5V07iFmJvmfaITX+GYVnibQK7cHBpwgvP3Jf7dRN",
	"HCTrJp0VJB+0u6bkXe5h1xVQXRFTfZEA+TMy0OzWiDIaEVqlKXkK+UAzxiLANENPD7bDxGucgT5peL0h",
	"3uPOm5Xpih513z3kewcLwJHG674d4uKM00nL7kGWFL7BNbXre61N/wtt43j7nNbjF+t1fHIKZ7+d/34E",
	"b/4xOzo+8U+P8Nlv50dnJ+fnx2fHv59NJhPHdWL8fAs0kKEzPT13nZjQ8p/VdXWd56OAHWUf05T4I023",
	"9P2IxAnjRp5YjeIERIbpbOSxeBwwFkQwVh31LL5QnMqQcfJf2M2BK3d0EaELHBEfMZ4fWCR7hI7H5J82",
	"99ewY8X0Zz1H65kq/6krPz+nnsr27sBT6LsrqqiuyivTffdAFUO6Nbjy83Ozq8hrrPtXJgkN9jttmL57",
	"nzeUrwleyolc3quZGUoC9En5grFHoukR5Xx65k/XMfNdtyrI4ITcgIKylesQOmcW/5UottE3mCGcJBHx",
	"sMxO5DF+BO3yiBArZpWP+8SJlECRVF4QYEGAjxQ1IvXUP7AZ85eICPQJ+Bw8iY7QFXNcZwFcGHqT0WR0",
	"rETMEqA4Ic7UOR1NRqeOq4FMT3aMEzL29JF+HGQrmTCjeVXuv5EoQqYlwojCkzlSzhnXnCtVQE9Ehgij",
	"DEHV8ukpXvvONIudXBmnlWfrrHk4mRyrfzxGJZjTWUk84wfBaBEl3qaZtgiFXpKNw5Ri3UzGVxI6m0x6",
	"Y8ESpbJw0CkopTnrTzjWzcnCW7md4eG0Nx7qsS0LA3mjio06079q1vnX99V31xFpHGO+zLUMYaOckpjT",
	"BNbqqQcrK3y6BsGOCt9RxzW2Kh3Xq/uO+cvepFcPQGrprfXG7OirF7SvYpe26Y2Sz69iVb+C4tbVcq1G",
	"hS4qRR3/MEHT1bh0WgigSSk5yJTTUt5G5DCs1Z7RaInIXIeBMc8+xjp6U1PZK5DrKJfaFjiOQQeOlK3p",
	"jU/7vPm2lwV3N1XOLQlxp6jv95qu9qcym7kKy3q9zaN2khNYbPoQw87wC+8MivpZr45DLfLe5Dnkgfad",
	"96d1FNdmtzrQ0rwV4ShiT9lWpjY1AdRHmK6TmpWRNq38HmgWzH49K+9/N6wmojvthJPeiW/k3i0qY0u0",
	"D8gyIEu/yHLfAgcNzobJj27xgE2jwrnA1EdeBJiiNMnTx6KGOCZvmx33DsuvsKalmxbUnoMezH8w/37N",
	"/7Jqpk0mHwFetAR57iBmCxB6GC/lHKg0/kaezVYDjdC1ycGyJwoc6TGFa/4SIUmQ5JiKufJvyqk8kwgf",
	"oX/GiVzqgYQ+nvhEeJj74I9qKHKrhj5YEKkUmFhUoqWaZACQAUD6BRBtalngrAk9lBlvcRfMKSVXWsmQ",
	"QpR6Sr9m6nnJwMGZer0YwrJ6nSofBqsfrL5fq39vNU5E6FZPIitrG/9YJw1XBhEikFDHho80WpbyRCFb",
	"x4kLqPAw1aUYpYK5KkLcEO/RlGy8CkS4Vip5yrSNToc87UsCkLVExqJLLfUwA/IMyNMv8ih1RDgzdnO+",
	"aHc+uK626pwZMc3Bz0OtmPpZyWwZ3TZBplTTdXCOiK1erSUpUggsl+WACQMmvCAmGAWtJEjsVtuYKbnI",
	"ghbGjTE5T8R45mEol4NxFGOa4ihaZnot1KHFEKnBwWdOggC4YWwAhAEQBkB4BUAwSrdOaXhlG2/yFnRN",
	"4JZYhW5THEDKpWx1JNAVigcbitysv2xaSmup5WD3g933nMysWGarjZsa4GZL7+QR6JFM2mNhaoqTEAvI",
	"PQU7GmSkDw0P7BXZlkVuK78eMGHAhJfAhMw8d/UFsnuanSIHonbPFBHqRamvCGvnQHvCW6oqi6vMh+ow",
	"lG9pW5bbcl13AIUBFF6mnlJYlM0OBuos0SmHWVRaqi4acYryqrYQojpPXzJ+ePWW5Ztpf3O1pfU+nt0l",
	"abp8N4DPAD79gs/XdlzIASjUr0WU/I8qXpjHJC5C8B6dFzShypsVFmF8vNm4tGI6mDdkisk8MEJzNN0R",
	"SFVfJSx4JkK7cVb8XD+WcXB+U+0VkKY7VJuvfAzQNUBXv9D1p7bEDZyK9DsxLaGUCDA3UZJseGSuRSMy",
	"R4wCIgIlHIQSQq2S04z9gta18cqNrZ6y4UmbKuzdskA32ayBLeSk32SpYGCnc2VSvOeS+anmMNl6c+eq",
	"9LLHwQFi/ZGehqqUTGz5Nb0BEQdE7P8kKbqb6cp1krQxr5QdSksjbbmd9yvYeP/nRdurRH/zudH6/FY7",
	"yNTe2hqwZsCavu/qtQPEygzIF2sM2PRjPBwhHxYQsSRW/olp67hOyiNn6oRSJtPxOFLtQibk9M3kzcRZ",
	"fV/9LwAA//8Z+Li3e1sAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
